services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: bmw_datagrid_mysql
    env_file:
      - ./server/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bmw_network

  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bmw_datagrid_backend
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "${PORT}:5000"
    depends_on:
      - mysql
    volumes:
      - ./server/temp:/app/temp
    networks:
      - bmw_network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: bmw_datagrid_frontend
    env_file:
      - ./client/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bmw_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  bmw_network:
    driver: bridge
